apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y3h4h0hjt-go 
  janus-idp.io/tekton: y3h4h0hjt-go
  backstage.io/kubernetes-id: y3h4h0hjt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y3h4h0hjt-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml